[project]
name = "neurosync-player"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "librosa>=0.10.2.post1",
    "pandas>=2.2.3",
    "pygame>=2.6.1",
    "timecode>=1.4.1",
]
